### PR TITLE
colw/2378 disable withdrawl on zero delegations

### LINKED ISSUE #2378: Disable withdrawal when user doesn't have any delegations
**Describe the bug**

Attempting to do a withdrawal without delegations renders the following error on the modal:

`Withdrawal failed: JSON Missing msgs.`

**To Reproduce**

1. Sign in with an account with no delegations
2. Click withdraw and try to submit the transaction

**Expected behavior**

Show a message that user needs to delegate to be able to withdraw.

### PR DESCRIPTION
**Pull request by colw**
Closes #2378

**Description:**

Disable option to withdraw when the user has no rewards.

withdraw-zero

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [x] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/common/TmBalance.vue [hunk 1]
```diff
@@ -16,6 +16,7 @@
         <h3>Rewards</h3>
         <h2>{{ rewards }}</h2>
         <TmBtn
+          v-show="rewards > 0"
```
Comment (faboweb) [inline src/components/common/TmBalance.vue]: Why not disabling it? Hiding it does also hide the functionality.

Comment (colw) [reply src/components/common/TmBalance.vue]: Good question

It's a link, not a button, and perhaps 'dead text' could be confusing? I could do that and add a tool tip perhaps? Explaining why it's not 

Then again hiding it initially is maybe not a bad thing? As a user gets rewards it becomes intuitive why it's not there at the beginning (or again not present in the future)

I'll experiment, and post a gif.

Comment (colw) [reply src/components/common/TmBalance.vue]: @jbibla Do you have thoughts on this? I'm hesitant to 'disable' an anchor text. Not quite sure what it should look like. A more dull colour with no cursor pointer?

Comment (faboweb) [reply src/components/common/TmBalance.vue]: Ah! Sorry I was mistaken. I thought this is the button on the Actionmodal. I think this is fine.

**Comment by jbibla** [comment]
i think a nice improvement on this would be letting users click withdraw, but displaying a message on the withdraw modal that says "make a delegation to start earning rewards!" or something like that.
