### PR TITLE
colw/2637 withdraw from 1-5 validators at a time

### LINKED ISSUE #2637: Ledger Nano S is not able to process big transactions (i.e. many withdrawels)
**Describe the bug**

Ledger Nano S is not able to process big transactions. When I delegate to a bunch of validators and try to withdraw from all of them at once (default) the Ledger reports an error, that it received too many "tokens" which stands for too big of a transaction to fit into the memory of the Ledger.

**To Reproduce**

Delegate to many validators.
Withdraw

**Expected behavior**

I am able to withdraw rewards. An easy fix is to add a withdraw button to each validators page. We probably need to come up with a better solution later.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by colw**
Closes #2637 

**Description:**

Withdraw in one of two ways:

- Global withdraw: Will withdraw from the 5 validators with the highest rewards.
- Validator page withdraw: Withdraw from single validator only

Screenshot 2019-05-23 at 11 50 15

If there are no rewards from a given validator, the button is disabled:
Screenshot 2019-05-23 at 11 51 46

The modal supports both variations and displays a message when withdrawing globally.
Screenshot 2019-05-23 at 11 49 17

Message: `Note: Lunie withdraws only the top 5 rewards at a time.`

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/staking/ModalWithdrawRewards.vue [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    atoms,
+    viewDenom,
+    fullDecimals
+  },
+  props: {
+    validatorAddress: {
+      type: String,
+      required: true
+    },
+    rewards: {
```
Comment (faboweb) [inline src/components/staking/ModalWithdrawRewards.vue]: Thinking about the ActionModal webcomponent, does it make sense to make the rewards an input? Or would we wrap this in a controller?

Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]: Yep, I thought about this. I believe wrapping it in a controller is better.

IMHO, the Modals should be 'dumb' views, and at most receive data and forward user actions, but that's it. Separation of concerns.

Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]: (Note: This should apply to most views)

File: src/components/staking/ModalWithdrawRewards.vue [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+  >
+    <TmFormGroup
+      class="action-modal-form-group"
+      field-id="amount"
+      field-label="Amount"
+    >
+      <span class="input-suffix">{{ denom | viewDenom }}</span>
+      <TmField id="amount" :value="rewards | atoms | fullDecimals" readonly />
+    </TmFormGroup>
+    <span v-if="!validatorAddress" class="form-message">
```
Comment (faboweb) [inline src/components/staking/ModalWithdrawRewards.vue]: should the message show always or only when the user actually has more then 5 delegations?

File: src/components/staking/ModalWithdrawRewards.vue [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+      Note: Lunie withdraws only the top 5 rewards at a time.
```
Comment (faboweb) [inline src/components/staking/ModalWithdrawRewards.vue]:
```suggestion
      Note: Lunie withdraws only the top 5 rewards at a time. The Ledger Nano S can't process bigger transactions.
```

File: src/utils/index.js [hunk 4]
```diff
@@ -47,3 +47,41 @@ export const roundObjectPercentages = dataMap => {
 
   return resultObject
 }
+
+const cmpSecondElementDesc = (a, b) => {
+  return b[1] - a[1]
+}
+
+// Takes an object:
```
Comment (faboweb) [inline src/utils/index.js]: 👍  Nice comment!

File: src/vuex/modules/distribution.js [hunk 5]
```diff
@@ -95,21 +97,28 @@ export default ({ node }) => {
...
-      {
-        rootState: { session },
-        getters: { committedDelegations },
-        dispatch
-      },
-      { gas, gas_prices, password, submitType }
+      { rootState, getters, dispatch },
+      { gas, gasPrice, denom, validatorAddress, password, submitType }
     ) {
+      const top5Delegations = getTop5Delegations(getters.committedDelegations)
```
Comment (faboweb) [inline src/vuex/modules/distribution.js]: should only limit to 5 delegations if the user is using the Ledger Nano S, but we can figure this out once we have more signers

File: src/components/staking/ModalWithdrawRewards.vue (hunk 2 above)
Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]: 🤦‍♂ You're right!

File: src/components/staking/ModalWithdrawRewards.vue (hunk 3 above)
Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]:
```suggestion
      Note: Lunie withdraws only the top 5 rewards at a time, due to a limitation in the Ledger Nano S.
```

Comment (jbibla) [reply src/components/staking/ModalWithdrawRewards.vue]: thanks colw - i prefer that language!

File: src/components/staking/ModalWithdrawRewards.vue (hunk 2 above)
Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]: Actually, is it necessary? We could leave it there to inform the user regardless?

File: src/utils/index.js (hunk 4 above)
Comment (colw) [reply src/utils/index.js]: Fair call. Improved it 👍

File: src/components/staking/ModalWithdrawRewards.vue (hunk 2 above)
Comment (faboweb) [reply src/components/staking/ModalWithdrawRewards.vue]: I personally like to reduce noise that is not important to users. @jbibla preferences?

File: src/vuex/modules/distribution.js (hunk 5 above)
Comment (colw) [reply src/vuex/modules/distribution.js]: Indeed. There's some time to spare before the Nano X is in wide distribution, and we'll need to detect the difference. Is that right?

File: src/components/staking/ModalWithdrawRewards.vue (hunk 2 above)
Comment (colw) [reply src/components/staking/ModalWithdrawRewards.vue]: * It would have a minor impact on the message wording. The current phrasing is generic.

File: src/vuex/modules/distribution.js (hunk 5 above)
Comment (faboweb) [reply src/vuex/modules/distribution.js]: yep
