### PR TITLE
Ana/magical fix for undelegations 1 day short

### LINKED ISSUE #3796: Undelegation End Time seems to be off by 1 day (i.e. 1 day too short)
**Describe the bug**

We have already got two users reporting this. One of them was trying to Redelegate during the day he thought he could, but he actually needed 24h to ellapse to be able to do it.

**To Reproduce**

We can monitor if we have any pending undelegation, although the waiting time is kind of long

**Expected behavior**

21 days equals to 504h. We need to make sure that the calculation in the FE is correct and that pending undelegations keep being displayed while an undelegation is pending

### PR DESCRIPTION
**Pull request by Bitcoinera**
**Description:**

A small line change (almost), but a big step onward for Lunie 🤣 

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
To check it actually works (I know it is difficult to believe looking at the code) you can check the address `cosmos1rfg85mh5pmm5f0m05wmqg5qaknv3u7rfyqp36t` in Gaia testnet in develop/production and then in this branch.

Surprise!

**Comment by jbibla** [comment]
so....... what do you suggest?

**Comment by Bitcoinera** [comment]
> so....... what do you suggest?

Merge this! 🤩

And reopen the issue if we get any other complaints. But is seems the days number is actually good

**Comment by jbibla** [comment]
if the days number is not the issue, why would we remove the loading logic? this doesn't fix any problems.

if you think the issue was that it loaded too slowly, we can add a loading svg to the `TableUndelegation` component.

File: src/components/staking/Undelegations.vue [hunk 1]
```diff
@@ -1,12 +1,5 @@
 <template>
-  <div
-    v-if="
-      !$apollo.queries.undelegations.loading &&
-        undelegations &&
-        undelegations.length > 0
-    "
-    class="undelegations"
-  >
+  <div v-if="undelegations && undelegations.length > 0" class="undelegations">
```
Comment (faboweb) [inline src/components/staking/Undelegations.vue:2]: this just skips the loading check 🤷‍♂

**Comment by Bitcoinera** [comment]
> if you think the issue was that it loaded too slowly, we can add a loading svg to the `TableUndelegation` component.

Yeah, true, like in `DelegationsOverview`.

I just wonder, why does it work so well without the loading logic? Is it really needed?

I am remembering something about loading being deprecated somehow or am I wrong? 🤔

File: src/components/staking/Undelegations.vue (hunk 1 above)
Comment (Bitcoinera) [reply src/components/staking/Undelegations.vue:2]: yes, but I think this might be the issue, what got users confused...

**Comment by jbibla** [comment]
>  Is it really needed?

yes, we should account for loading.

>  am remembering something about loading being deprecated somehow or am I wrong?

not sure.

**Comment by Bitcoinera** [comment]
OK, I just copied now how it looks in the DelegationOverview so now this PR should be 100% safe.

Sorry if I have disappointed you with the PR title & bug and you were expecting real magic 😅

File: src/components/staking/Undelegations.vue [hunk 2]
```diff
@@ -1,9 +1,21 @@
 <template>
-  <div v-if="undelegations && undelegations.length > 0" class="undelegations">
-    <h1>
-      Pending
-    </h1>
-    <TableUndelegations :undelegations="undelegations" />
+  <div class="table-container">
+    <div
+      v-if="$apollo.queries.undelegations.loading && !undelegations.length"
```
Comment (faboweb) [inline src/components/staking/Undelegations.vue:4]: you need a `undelegationsLoaded` property here. if no, this will show loading all the time when some update is triggered but you have no undelegations

**Comment by Bitcoinera** [comment]
I updated the PR description since I don't think this will really close #3796...

Instead, I will make a new 3 days undelegation, very well documented, and without DST in the middle to better understand what is really happening here.

**Comment by Bitcoinera** [comment]
Still, I think this is a good PR to merge

File: src/components/staking/DelegationsOverview.vue [hunk 3]
```diff
@@ -1,7 +1,11 @@
 <template>
   <div class="table-container">
     <div
-      v-if="$apollo.queries.delegations.loading && !delegations.length"
+      v-if="
+        $apollo.queries.delegations.loading &&
+          !delegationsLoaded &&
+          !delegations.length
```
Comment (faboweb) [inline src/components/staking/DelegationsOverview.vue:7]:
```suggestion
          !delegationsLoaded
```

File: src/components/staking/Undelegations.vue [hunk 4]
```diff
@@ -1,16 +1,25 @@
...
-    <h1>
-      Pending
-    </h1>
-    <TableUndelegations :undelegations="undelegations" />
+  <div class="table-container">
+    <div
+      v-if="
+        $apollo.queries.undelegations.loading &&
+          !undelegationsLoaded &&
+          !undelegations.length
```
Comment (faboweb) [inline src/components/staking/Undelegations.vue:7]:
```suggestion
          !undelegationsLoaded
```

File: src/components/staking/Undelegations.vue [hunk 5]
```diff
@@ -1,16 +1,25 @@
...
+      "
+      class="loading-image-container"
+    >
+      <img
+        class="loading-image"
+        src="/img/portfolio-loading.svg"
+        alt="geometric placeholder shapes"
+      />
+    </div>
+    <div v-if="undelegations.length > 0" class="undelegations">
```
Comment (faboweb) [inline src/components/staking/Undelegations.vue:17]:
```suggestion
    <div v-else-if="undelegations.length > 0" class="undelegations">
```
