### PR TITLE
Fix NaN self stake % in inactive validator in Polkadot

### LINKED ISSUE #3931: Wrong Self Stake percentage for inactive validators in polkadot
**Describe the bug**

Wrong self stake percentage for inactive validators in polkadot, API is returning the data correctly (`"selfStake": "0.000000000"`) so this is a frontend issue.

**To Reproduce**
1. Select Kusama network
2. Go to validators and click on a inactive validator
3. Self stake percentage is -NaN%

**Expected behavior**
Should show 0% for inactive validators in polkadot.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3931 

**Description:**

Handle undefined caused by 0/0 div.

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [x] Attach screenshots of the UI components on the PR description (if applicable)
- [x] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/staking/PageValidator.vue [hunk 1]
```diff
@@ -144,7 +144,7 @@
           <h4>Self Stake</h4>
           <span id="page-profile__self-bond">
             {{ validator.selfStake | shortDecimals }} /
-            {{ (validator.selfStake / validator.tokens) | percent }}
+            {{ (validator.selfStake / validator.tokens || 0) | percent }}
```
Comment (faboweb) [inline src/components/staking/PageValidator.vue:147]: Nice I didn't know that this works

**Comment by Bitcoinera** [comment]
👀  GitHub bug
