### PR TITLE
Fix gas price input deselects itself after typing

### LINKED ISSUE #3333: gas price input deselects itself after typing
**Describe the bug**

- the gas price input defaults to a number. if you select the input and delete or change the number the input deselects.

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3333 

**Description:**

Fix gas price input deselects itself after typing.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/common/TmField.vue [hunk 1]
```diff
@@ -175,6 +175,9 @@ export default {
       this.$emit(`input`, formattedValue)
     },
     onChange(...args) {
```
Comment (jbibla) [inline src/components/common/TmField.vue]: 2 questions: 

- is this onChange even necessary? 
- why do `number` inputs have to be treated differently?

Comment (mariopino) [reply src/components/common/TmField.vue]: Yes, onChange is needed to update parent's data. I currenly have no answer for second :-(
