### PR TITLE
Ana/fix all addresses deleted glitch

### LINKED ISSUE #5097: All accounts apparently deleted when deleting single account on Extension
This is a small but shocking glitch on the current extension version, as you could appreciate to day in the demo.

Fortunately, it is just a glitch and only the desired account gets deleted

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #5097 

**Description:**

Thanks for the heads up @faboweb . Yes, `response` was `null` and thus deleting all accounts in store momentarily. Easy fix

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: extension/src/store/actions.js [hunk 1]
```diff
@@ -77,14 +77,17 @@ export default ({ apollo }) => {
...
 
-  const deleteAccountWithoutPassword = async ({ commit }, { address }) => {
+  const deleteAccountWithoutPassword = async (store, { address }) => {
     chrome.runtime.sendMessage(
       {
         type: 'DELETE_WALLET_WITHOUT_PASSWORD',
         payload: { address }
       },
-      function (response) {
-        commit('setAccounts', response || [])
```
Comment (faboweb) [inline extension/src/store/actions.js:87]: instead you should have send the remaining accounts back from background.js as stated in the issue

**Review by faboweb — APPROVED** [review]
