### PR TITLE
Ana/4094 account role detection on switching networks

### LINKED ISSUE #4094: Stash/ controller account detection: wrong on change network
When switching networks our current system for accountRole detection is not working.

For example:

image

Not good:

image

### LINKED ISSUE #4096: DelegationModal looks quite wrong
Maybe changes while dealing with account role detection. DelegationModal now looks like this (for ALL networks, no matter the account role (except stash)):

~~Notice that "From" and "To" are reversed~~ and also that weird 0. Fixing

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4094
Closes #4096 

**Description:**

Works better with luniehq/lunie-api#798.
Also works without it but better not throw any errors, just return `undefined`

Fixes the account role detection not working when switching networks.

Bonus extra. add loading state to button on ActionModal for `feeStep`

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/vuex/modules/session.js [hunk 1]
```diff
@@ -153,12 +153,10 @@ export default ({ apollo }) => {
         addresses,
       })
 
-      if (currentNetwork.network_type === "polkadot") {
-        await dispatch(`checkAddressRole`, {
-          address,
-          networkId: currentNetwork.id,
-        })
-      }
+      await dispatch(`checkAddressRole`, {
```
Comment (faboweb) [inline src/vuex/modules/session.js:156]:
```suggestion
      // In Polkadot there are different account types for staking. To be able to signal allowed interactions
      // for the user in Lunie we need to query for the type of the account.
      await dispatch(`checkAddressRole`, {
```

**Comment by faboweb** [comment]
Great find @Bitcoinera

File: src/vuex/modules/session.js [hunk 2]
```diff
@@ -155,10 +155,14 @@ export default ({ apollo }) => {
...
-        address,
-        networkId: currentNetwork.id,
-      })
+      if (currentNetwork.network_type === 'polkadot') {
+        await dispatch(`checkAddressRole`, {
+          address,
+          networkId: currentNetwork.id,
+        })
+      } else {
+        commit(`setUserAddressRole`, undefined)
```
Comment (Bitcoinera) [inline src/vuex/modules/session.js:164]: Great!

Still a mystery to me why this was causing E2E to fail 🤷
