### PR TITLE
Don't fetch polkadot proposals if feature is not enabled

### LINKED ISSUE #5112: Error in API: Cannot read property 'proposals' of undefined
**Describe the bug**

This error happens when query all proposals for westend (doesn't have governance enabled), so we need to avoid that query for networks that without governance feature enabled.

```
node:8468) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'proposals' of undefined
    at polkadotAPI.getAllProposals (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\api\lib\source\polkadotV0-source.js:1016:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PolkadotNodeSubscription.pollForProposalChanges (C:\_Datos_2018\1.Proyectos\_BlockChain\Lunie\_DEV\lunie\api\lib\block-listeners\base-node-subscription.js:65:18)
(node:8468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #5112 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: api/lib/source/polkadotV0-source.js [hunk 1]
```diff
@@ -1001,7 +1001,7 @@ class polkadotAPI extends BaseRESTDataSource {
   }
 
   async getAllProposals() {
-    if (this.network.feature_proposals === 'DISABLED') {
+    if (this.network.feature_proposals !== 'ENABLED') {
```
Comment (Bitcoinera) [inline api/lib/source/polkadotV0-source.js:1004]: ah, of course, because for eMoney and Westend this feature is missing

**Review by Bitcoinera — APPROVED** [review]
