### PR TITLE
Ana/3738 & fix address is null

### LINKED ISSUE #3738: Loading delay on opening action modals
There is still a lot of loading strangely in places where the networks should already loaded. Like when opening the ActionModal (i.e. Withdraw Modal) there should not be any loading

### LINKED ISSUE #3855: Object.a
Sentry Issue: [FRONTEND-8T](https://monitoring.lunie.io:9000/lunie/frontend/issues/373/?referrer=github_integration)

```
Error: Non-Error exception captured with keys: extensions, locations, message, path
  at Object.a (/bundles/c31fcd422fdbfb1f8688748e08295f8af352cf03.js:45:128486)
  at None (/bundles/c31fcd422fdbfb1f8688748e08295f8af352cf03.js:74:51446)
  at Array.map (<anonymous>)
  at Object.next (/bundles/c31fcd422fdbfb1f8688748e08295f8af352cf03.js:74:51393)
  at w (/bundles/c31fcd422fdbfb1f8688748e08295f8af352cf03.js:65:10227)
...
(17 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Bitcoinera**
Fixes address is null in Action Modal
Closes #3738 (this one for sure)

**Description:**

The error I encountered when following the steps from [this sentry error](https://monitoring.lunie.io:9000/lunie/frontend/issues/373/?referrer=github_integration) is slightly different than anything with an `Object.a`, but it was `variable $address is null` or something similar.

The reason is because acting on the `open` method, the ActionModal was still triggering the smartqueries despite the skips.

I have found some code there with `skipAll` kind of cumbersome (and actually here was the bug for the skips not being triggered) and also have not seen the need of the `loaded` logic at all. Removing the `loaded` logic makes the ActionModals open automatically (fixes #3738)

The only problem I have left is the test for the TmDataLoading. But maybe it failing like this means something is still wrong.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/ActionModal/components/ActionModal.vue [hunk 1]
```diff
@@ -45,7 +45,7 @@
       <template v-if="!checkFeatureAvailable">
         <FeatureNotAvailable :feature="title" />
       </template>
-      <TmDataLoading v-else-if="!loaded" />
+      <TmDataLoading v-else-if="$apollo.loading && !$apollo.skipAll" />
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:48]: why?

File: src/ActionModal/components/UndelegationModal.vue [hunk 2]
```diff
@@ -375,13 +375,13 @@ export default {
       `,
       /* istanbul ignore next */
       skip() {
-        return !this.userAddress
+        return !this.address
```
Comment (faboweb) [inline src/ActionModal/components/UndelegationModal.vue:378]: ok nice find

File: src/ActionModal/components/DelegationModal.vue [hunk 3]
```diff
@@ -358,6 +358,9 @@ export default {
       /* istanbul ignore next */
       update(data) {
         return data.validators
+      },
+      skip() {
+        return !this.address
```
Comment (faboweb) [inline src/ActionModal/components/DelegationModal.vue:363]: top

File: src/ActionModal/components/ActionModal.vue [hunk 4]
```diff
@@ -597,7 +591,11 @@ export default {
       }
     },
     async open() {
-      this.$apollo.skipAll = false
+      if (!this.address) {
+        this.$apollo.skipAll = true
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:595]: do we need this?

File: src/ActionModal/components/ActionModal.vue (hunk 1 above)
Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue:48]: `loaded` was introducing too much unnecessary complexity and was responsible for the never loading modals bug. 
Also, if we set `skipAll` to true, it doesn't make sense to wait for data. I think this is the most logical.

File: src/ActionModal/components/ActionModal.vue (hunk 4 above)
Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue:595]: I tried getting rid of `skipAll` altogether, but then a bunch of tests were failing... I can look further into that

File: src/ActionModal/components/ActionModal.vue (hunk 1 above)
Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue:48]: loaded != $apollo.loading. loading changes every loading call loaded changes only after the first load

**Comment by Bitcoinera** [comment]
Good to go! Fixes two bugs in one 😉 And one (ActionModal getting hung) is an old one

File: src/ActionModal/components/ActionModal.vue (hunk 1 above)
Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: ping

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue]: I changed to `$apollo.queries.<query>.loading`, but it is probably the same.

I will just copy from Undelegations table. There I remember it had the proper logic

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: using "loading" will show the loader on every apollo load of balances or overview

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue]: Yes, I was thinking. Thank you for confirming. I just fixed the logic of it all

File: src/ActionModal/components/ActionModal.vue [hunk 5]
```diff
@@ -47,7 +47,8 @@
       </template>
       <TmDataLoading
         v-else-if="
-          $apollo.queries.overview.loading || $apollo.queries.balances.loading
+          $apollo.loading &&
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:50]: whyyyy? still loading there

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue:50]: hmm maybe your right, need to try it out. as we load some stuff on every step, right?

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue:50]: I can confirm this works, but you're free to try it out. Like you said, `$apollo.loading` is true if any of the three queries (balances, overview and gasEstimate) is still loading

File: src/ActionModal/components/DelegationModal.vue (hunk 3 above)
Comment (jbibla) [reply src/ActionModal/components/DelegationModal.vue:364]: what does "top" mean?

File: src/ActionModal/components/ActionModal.vue (hunk 5 above)
Comment (jbibla) [reply src/ActionModal/components/ActionModal.vue:50]: this is not a good strategy from a ux perspective. the step should always load instantly. if there is data that is being loaded we should show a loader inline with the data and restrict the user from going forward. blocking this components like this is no bueno.

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue:50]: Sounds cool, I like the idea. So basically what you are proposing is loading as you go, show what you have at each point, right?

**Comment by Bitcoinera** [comment]
Please, let's merge 😆

File: src/ActionModal/components/DelegationModal.vue (hunk 3 above)
Comment (faboweb) [reply src/ActionModal/components/DelegationModal.vue:364]: 🔝 👍
