### PR TITLE
Ana/fix getting single validator for akash

### LINKED ISSUE #4678: akash validator profile won't load
**Describe the bug**

spinning wheel never goes away

on production there are no console errors - on staging i see an `Uncaught (in promise) undefined` in vue-router so possibly a missing network ID?

https://staging--lunieio.netlify.app/akash-testnet/validators/akashvaloper1n2dpzlx4y2lsnvvzsa7np00a4kddm62w5aj0ue

@gosuri

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4678 

**Description:**

Fixed! It was this new `getCoinLookup` messing things up

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: api/lib/reducers/akashV0-reducers.js [hunk 1]
```diff
@@ -18,18 +18,15 @@ function setTransactionSuccess(transaction) {
...
-  )
+function delegationReducer(delegation, validator) {
   return {
     id: delegation.validator_address,
     validatorAddress: delegation.validator_address,
     delegatorAddress: delegation.delegator_address,
     validator,
-    amount: delegationCoin.amount
+    amount: delegation.balance
+      ? terraV3Reducers.atoms(delegation.balance.amount)
```
Comment (faboweb) [inline api/lib/reducers/akashV0-reducers.js:28]: this doesn'T look right. where does .atoms gets the precision from?

Comment (faboweb) [reply api/lib/reducers/akashV0-reducers.js:28]: let's improve later

**Comment by faboweb** [comment]
testing and linting fails
