### PR TITLE
Don't show apollo loading when searching

### LINKED ISSUE #3131: loading screen appears when using search bar
**Describe the bug**

loading screen appears when using search bar but underneath results - this is probably not intended

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3131 

**Description:**

Don't show the loading screen when using search bar.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/staking/PageValidators.vue [hunk 1]
```diff
@@ -32,7 +32,7 @@
       >
         No results for these search terms
       </div>
-      <TmDataLoading v-if="$apollo.loading" />
+      <TmDataLoading v-if="$apollo.loading && !searchTerm" />
```
Comment (faboweb) [inline src/components/staking/PageValidators.vue]: Nice and simple!
I will accept the solution but want to share that there might be an issue in the future:
Imagine a slow connection, validators are still loading but the user is already searching. The loader would disappear. Therefor it would be better to actually set a `loaded=true` after the validators are loaded in the `result` hook. Check PageValidator
