### PR TITLE
Fix redelegation

### LINKED ISSUE #3096: unstaking and clicking redelegation sets the to and from fields incorrectly
if i go to unstake from a validator, but i click the redelegate button - the "to" field becomes the validator i was intending to unstake from. this should be the opposite. 

ideally, i'd propose we just use dropdowns for both "to" and "from" on the redelegation modal.

as well, maybe we should just put dropdowns for "to" and "from" for all staking modals.

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3096 

**Description:**

- Implement redelegation as a specific case of undelegation.
- Show delegations in `From` field and list of active validators (excluding source validator) in `To` field.

**Pending tasks:**

- Delete redelegation logic in DelegationModal.vue
- Testing
- Code coverage
- Improve redelegation constraints handling, new PR: https://github.com/luniehq/lunie/issues/3325

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/ActionModal/components/DelegationModal.vue [hunk 1]
```diff
@@ -52,7 +58,37 @@
...
 
     <TmFormGroup
-      v-if="fromOptions.length > 1"
+      v-else
+      class="action-modal-form-group"
+      field-id="to"
+      field-label="To"
+    >
+      <TmField
+        id="to"
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: i think the `from` field should be above the `to` field.

File: src/ActionModal/components/DelegationModal.vue [hunk 2]
```diff
@@ -52,7 +58,37 @@
...
+        v-model="targetValidator.operatorAddress"
+        :options="validators"
+        type="select"
+      />
+      <TmFormMsg
+        v-if="targetValidator.status === 'INACTIVE' && !isRedelegation"
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: instead of showing this, should we only list active validators in the dropdown?

File: src/ActionModal/components/DelegationModal.vue [hunk 3]
```diff
@@ -374,6 +443,63 @@ export default {
...
+        ) {
+          validators(
+            networkId: $networkId
+            searchTerm: $searchTerm
+            activeOnly: $activeOnly
+          ) {
+            name
+            operatorAddress
+            consensusPubkey
+            votingPower
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: why do we need all this validator data just to populate the list?

File: src/ActionModal/components/DelegationModal.vue [hunk 4]
```diff
@@ -374,6 +443,63 @@ export default {
...
+                key: `${validator.name} - ${formatBech32(
+                  validator.operatorAddress,
+                  false,
+                  20
+                )}`,
+                value: validator.operatorAddress
+              }
+            })
+        )
+        // console.log(options)
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: you can delete this comment 😉

File: src/ActionModal/components/DelegationModal.vue [hunk 5]
```diff
@@ -52,7 +58,37 @@
...
     <TmFormGroup
-      v-if="fromOptions.length > 1"
+      v-else
+      class="action-modal-form-group"
+      field-id="to"
+      field-label="To"
+    >
+      <TmField
+        id="to"
+        v-model="targetValidator.operatorAddress"
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: how much work would it be to show the picture (like we do in the activity page) in the dropdown 😄 ?

Comment (jbibla) [reply src/ActionModal/components/DelegationModal.vue]: and, would it be possible (how much work?) if we changed the page of the validator when a user selected a validator from this list? would that be strange ux? just a thought...

Comment (faboweb) [reply src/ActionModal/components/DelegationModal.vue]: #scopecreep

**Comment by faboweb** [comment]
I don't like the double dropdown. It increases complexity as it increases the simultanious decisions a user needs to make. I know @jbibla proposed this as a solution and I am pretty late to protest.

**Comment by mariopino** [comment]
> I don't like the double dropdown. It increases complexity as it increases the simultanious decisions a user needs to make. I know @jbibla proposed this as a solution and I am pretty late to protest.

Well, we can simplify user options just maintaining the To field and remove From. What do you think?

File: src/ActionModal/components/DelegationModal.vue (hunk 5 above)
Comment (mariopino) [reply src/ActionModal/components/DelegationModal.vue]: > and, would it be possible (how much work?) if we changed the page of the validator when a user selected a validator from this list? would that be strange ux? just a thought...

mmm I think would be strange :-), but useful because then users could see helpful information about the possible validators to redelegate (like comission or voting power), half hided by the modal window thought xD.

mmm may be a dumb question but why we need modal windows? Shouldn't be easier to use the same layaout for all actions? For example in this case we are limited by the modal window size...

Just a thought! don't want to reinvent the world ;-)

Comment (jbibla) [reply src/ActionModal/components/DelegationModal.vue]: > #scopecreep

**Definitely, but sometimes it's nice to take these opportunities to discuss new ideas - however always good to assume these things will happen in another PR! 

> why we need modal windows

what do you mean @mariopino ?

**Comment by jbibla** [comment]
> It increases complexity as it increases the simultanious decisions a user needs to make.

while this is true, i think it's ok because the user has already indicated that they want to do something more complicated (redelegate).

however, i don't feel super strongly about this. 

the thing i do care about is that the `to` and `from` are not backwards as they were before.

**Comment by faboweb** [comment]
> the thing i do care about is that the to and from are not backwards as they were before.

can we revert to just this change?

**Comment by mariopino** [comment]
> > the thing i do care about is that the to and from are not backwards as they were before.
> 
> can we revert to just this change?

Oki, I will just fix the to field.

**Comment by jbibla** [comment]
yep you got it mario! 

i would leave the from field but have it disabled as we do for the delegation modal. users have in the past wanted to see this.

i will add:
- remove the "redelegation" link from the undelegation modal
- undelegation modal should include a "To" input, which is a dropdown with a default of "My Wallet" selected. the rest of the validators should appear as the other options in the dropdown.

this should be simple and will address the issue in the short term. long term we will have to re-assess the UX around these transactions. 

hope this is clear and makes sense.

**Comment by faboweb** [comment]
Great! Almost done!
I would appreciate a test for the `update` functions in the 2 modals
And for the `setFromSelectedIndex` in `UndelegationModal`

**Comment by mariopino** [comment]
> Great! Almost done!
> I would appreciate a test for the `update` functions in the 2 modals

Hey @faboweb! My plan was to keep redelegation logic only in `UndelegationModal.vue` and removing it from `DelegationModal.vue`, what do you think?

> And for the `setFromSelectedIndex` in `UndelegationModal`

Sure! I want to do some (quick) cleanup before and check variable names again to make sure their names provide valuable information.

**Comment by faboweb** [comment]
test for `update` missing for DelegationModal

**Comment by faboweb** [comment]
Looking good!!!

File: src/ActionModal/components/DelegationModal.vue [hunk 6]
```diff
@@ -91,8 +76,7 @@
         />
       </TmFieldGroup>
       <span class="form-message">
-        {{ isRedelegation ? "Available to redelegate" : "Available to stake" }}
-        :
+        Available to stake:
         {{ maxAmount }}
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: will `maxAmount` change to reflect your current delegation if you're doing a redelegation? or always shows available balance?

File: src/ActionModal/components/UndelegationModal.vue [hunk 7]
```diff
@@ -4,9 +4,11 @@
     ref="actionModal"
     :validate="validateForm"
     :amount="0"
-    title="Unstake"
+    :title="isRedelegation ? 'Restake' : 'Unstake'"
```
Comment (jbibla) [inline src/ActionModal/components/UndelegationModal.vue]: apologies for the all the miscommunication here.

i think we should remove redelegation from this component as well. both delegation and undelegation modals should include to and from fields that are dropdowns.

**Comment by faboweb** [comment]
@mariopino there are some comments here, did you see them?

**Comment by mariopino** [comment]
> @mariopino there are some comments here, did you see them?

Hey @faboweb, yes, I have to address them and finish the issue.

**Comment by faboweb** [comment]
Success is not triggered for me. Is that an API issue or an issue with this PR?

There is some dropdown showing even if I can't use it:
image

**Comment by mariopino** [comment]
> Success is not triggered for me. Is that an API issue or an issue with this PR?
> 
> There is some dropdown showing even if I can't use it:
> image

We can enable it to show all validators in `To` field, it's an easy modification.

**Comment by faboweb** [comment]
> We can enable it to show all validators in To field, it's an easy modification.

but we don't right now. should we keep code we don't use in there?
