### PR TITLE
Ana/easy fix for network not available in router

### LINKED ISSUE #4127: Networks not available in router feature detection logic
Sentry Issue: [FRONTEND-K1](https://monitoring.lunie.io:9000/lunie/frontend/issues/815/?referrer=github_integration)

```
TypeError: Cannot read property 'feature_portfolio' of undefined
  at _callee2$ (webpack-internal:///56d7:2563:68)
  at tryCatch (webpack-internal:///96cf:45:40)
  at Generator.invoke [as _invoke] (webpack-internal:///96cf:274:22)
  at Generator.prototype.<computed> [as next] (webpack-internal:///96cf:97:21)
  at asyncGeneratorStep (webpack-internal:///c973:3:24)
...
(28 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4127 
**Description:**

Maybe you call this cheating @faboweb , but I really think it is way to go.

Making the function `featureAvailable` super safe. Bug killed!

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -73,9 +67,13 @@ async function featureAvailable(store, networkSlug, feature) {
...
-    : // DEPRECATE fallback for old API response
-      networkCapabilityDictionary[currentNetwork[featureSelector]]
+  if (currentNetwork) {
+    const featureSelector = `feature_${feature.toLowerCase()}`
+    return currentNetwork[featureSelector]
+  } else {
+    setTimeout(
+      async () => await featureAvailable(store, networkSlug, feature),
+      100
+    )
```
Comment (faboweb) [inline src/router.js:77]:
```suggestion
    await new Promise(resolve => setTimeout(resolve, 100))
    return featureAvailable(store, networkSlug, feature)
```

Comment (faboweb) [reply src/router.js:77]: Though: this would loop endlessly with a wrong networkSlug or id. Better move the loop up and check if the networks where loaded?

Comment (Bitcoinera) [reply src/router.js:77]: ah yeah, good point

File: src/router.js [hunk 2]
```diff
@@ -60,20 +60,18 @@ export default Router
 
 // check if feature is allowed and redirect if not
 async function featureAvailable(store, networkSlug, feature) {
-  const networks = store.state.connection.networks
+  let networks = store.state.connection.networks
+  if (networks.length === 0) {
+    await new Promise((resolve) => setTimeout(resolve, 100))
+    featureAvailable(store, networkSlug, feature)
```
Comment (faboweb) [inline src/router.js:66]:
```suggestion
    return featureAvailable(store, networkSlug, feature)
```

Comment (Bitcoinera) [reply src/router.js:66]: what is the difference?

Comment (Bitcoinera) [reply src/router.js:66]: I mean, I tested and it works

Comment (faboweb) [reply src/router.js:66]: without this the execution of the async function ` featureAvailable(store, networkSlug, feature)` doesn't really matter

Comment (Bitcoinera) [reply src/router.js:66]: Ok ok, I change it

Comment (Bitcoinera) [reply src/router.js]: Done
