### PR TITLE
Ana/4525 cleaning up notifications Part 1

### LINKED ISSUE #4525: Cleaning up notifications
**now**
- [x] user menu ghost icon is not centred on windows
- [x] "Add an address" should go in user menu
- [x] `CardSignIn` should be modal instead of in page component
- [x] paywall variables and scroll bugs
- [x] message after sign in toggles states should be a modal that displays which addresses you'll receive notifications about -> link and CTA should go to notifications page
- [x] voting power changes message is broken (should show %)
- [x] remove new validator notification for now (and use network icon instead of lunie logo - for future use)
- [x] lunie theme on notifications page instead of network theme
- [x] hide app menu - add logo - deselect current network when on notifications page
- [x] notifications becomes home page / landing page if user is signed in with email
- [x] magic link copy needs to be updated
- [x] click the notifications icon from the paywall and the app gets stuck on a loading screen
- [x]  take user out from notifications back to Paywall when they sign out being on the notifications page

**next**
---
- [ ] connect user emails via intercom
- [ ] drip campaign 
- [ ] only display notifications that go back 30 days
- [ ] every user should have 1 notification from Lunie that says welcome

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #4525

**Description:**

- [x] "Add an address" should go in user menu
- [x]  CardSignIn should be modal instead of in page component
- [x] remove new validator notification for now (and use network icon instead of lunie logo - for future use)

Work in progress

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by faboweb** [comment]
🚀 Deployed on https://5f105a1b597266578eed9a6a--lunieio.netlify.app

File: api/lib/notifications.js [hunk 1]
```diff
@@ -166,6 +166,8 @@ function getIcon({ eventType, data }) {
     case eventTypes.PROPOSAL_CREATE:
     case eventTypes.PROPOSAL_UPDATE:
       return `/img/icons/activity/Submitted.svg`
+    case eventTypes.VALIDATOR_ADDED:
+      return `/img/networks/${notificationData.nextValidator.networkId}.png`
```
Comment (jbibla) [inline api/lib/notifications.js:170]: what image is this? i think we meant just remove the `VALIDATOR_ADDED` notification for users - but we don't want to delete the notification because it will be used for network profiles and validator profiles

File: app/src/components/common/CardSignInRequired.vue [hunk 2]
```diff
@@ -118,6 +121,7 @@ h3 {
   padding: 0 1rem 5rem;
   margin: 0 auto;
   width: 100%;
+  overflow: auto;
```
Comment (jbibla) [inline app/src/components/common/CardSignInRequired.vue:124]: why is this needed?

File: app/src/components/common/SessionFrame.vue [hunk 3]
```diff
@@ -65,15 +65,27 @@ export default {
   },
   methods: {
     goBack() {
-      this.$router.go(`-1`)
+      if (location.href.includes(`portfolio`)) {
+        this.$router.push({
+          name: "networks"
```
Comment (jbibla) [inline app/src/components/common/SessionFrame.vue:70]: why not always `this.$router.go(`-1`)`?

File: api/lib/notifications.js (hunk 1 above)
Comment (Bitcoinera) [reply api/lib/notifications.js:170]: yes, this is the second part: ` remove new validator notification for now **(and use network icon instead of lunie logo - for future use)**`

I tried to do the first part but failed in a first attempt

File: app/src/components/common/CardSignInRequired.vue (hunk 2 above)
Comment (Bitcoinera) [reply app/src/components/common/CardSignInRequired.vue:124]: CardSignInRequired was "losing" the top. It wasn't being displayed

File: app/src/components/common/SessionFrame.vue (hunk 3 above)
Comment (Bitcoinera) [reply app/src/components/common/SessionFrame.vue:70]: because then you get a double navigation error when you are already on portfolio (CardSignInrequired) and try to navigate to portfolio again

Comment (Bitcoinera) [reply app/src/components/common/SessionFrame.vue:70]: ah yeah, but why this happens :thinking: I will recheck

**Comment by jbibla** [comment]
thanks for getting started here ana! 

as fabo said, please don't add more from the original ticket so we don't duplicate work!

**Comment by Bitcoinera** [comment]
> as fabo said, please don't add more from the original ticket so we don't duplicate work and we keep the PR small!

OK, I will stop on these three/issues for this PR :pray:

**Comment by Bitcoinera** [comment]
Needs #4534 to work properly

**Comment by Bitcoinera** [comment]
Ugh, these buttons :facepalm:

File: app/src/components/common/CardSignInRequired.vue (hunk 2 above)
Comment (jbibla) [reply app/src/components/common/CardSignInRequired.vue:124]: the session modal should handle this though

File: api/lib/notifications/notifications.js [hunk 4]
```diff
@@ -274,14 +275,16 @@ const getNotifications = (networks) => async (
...
-  const notifications = relevantNotifications.map((notification) => ({
-    id: notification.id, // used for correctly handling cache in Apollo
-    networkId: notification.networkId, // used for filtering per network
-    timestamp: notification.created_at, // used for grouping / sorting
-    title: getMessageTitle(networks, notification), // title of notification
-    link: getPushLink(networks, notification), // link for click-through action
-    icon: getIcon(notification) // icon link
-  }))
+  const notifications = relevantNotifications
+    .filter(({ eventType }) => eventType !== `validatorAdded`)
```
Comment (faboweb) [inline api/lib/notifications/notifications.js:279]:
```suggestion
    .filter(({ eventType }) => eventType !== eventTypes.VALIDATOR_ADDED)
```

**Comment by faboweb** [comment]
Clicking "Add an address" and then "close" will not close the sign in modal. It should go to the last route without needed sign in or the validators page of the current / default network.

File: app/src/components/network/NetworkItem.vue [hunk 5]
```diff
@@ -24,7 +24,7 @@
         <i class="material-icons notranslate">check</i>
       </div>
       <img
-        v-else-if="disabled && isCurrentNetwork"
+        v-else="disabled && isCurrentNetwork"
```
Comment (jbibla) [inline app/src/components/network/NetworkItem.vue:27]:
```suggestion
        v-else-if="disabled && isCurrentNetwork"
```

File: app/src/main.js [hunk 6]
```diff
@@ -53,5 +53,18 @@ init(urlParams).then(({ store, router, apolloProvider }) => {
         StatusBar.show()
       }
     },
+    watch: {
+    '$route': {
+      handler: function () {
```
Comment (faboweb) [inline app/src/main.js:58]: 🤮

File: app/src/components/common/SessionFrame.vue [hunk 7]
```diff
@@ -65,15 +65,25 @@ export default {
...
     },
-    goToPortfolio() {
-      this.$router.push({
-        name: "portfolio",
-        params: {
-          networkId: this.networkSlug,
-        },
-      })
+    closeModal() {
+      if (this.$route.meta.requiresAuth) {
```
Comment (faboweb) [inline app/src/components/common/SessionFrame.vue:77]: sweet

File: app/src/main.js [hunk 8]
```diff
@@ -53,5 +53,18 @@ init(urlParams).then(({ store, router, apolloProvider }) => {
...
+          if (this.$route.name === `notifications`) {
```
Comment (faboweb) [inline app/src/main.js:59]: let's change this soon. ok for now

File: app/src/main.js (hunk 6 above)
Comment (jbibla) [reply app/src/main.js:58]: ana really dislikes this emoji

File: app/src/main.js (hunk 8 above)
Comment (jbibla) [reply app/src/main.js:59]: i don't think we need this actually - i will remove this watch function
