### PR TITLE
RTM: Prevent bad amounts to be send

### LINKED ISSUE #3476: Prevent bad amounts to be send
Sentry Issue: [PRODUCTION-API-B](https://monitoring.lunie.io:9000/lunie/production-api/issues/164/?referrer=github_integration)

```
Error: {"error":"math/big: cannot unmarshal \"NaN\" into a *big.Int"}
  File "/var/www/server/lib/controller/transaction/index.js", line 83, in null.<anonymous>
    throw new Error(await res.text())
  ?, in runMicrotasks
  File "/var/www/server/lib/controller/transaction/index.js", line 73, in async broadcastTransaction
    const res = await fetch(`${url}/txs`, {
  File "/var/www/server/lib/controller/transaction/index.js", line 39, in async broadcast
    const hash = await broadcastTransaction(
...
(1 additional frame(s) were not displayed)
```

There was also an amount send in uatoms that was a decimal: https://monitoring.lunie.io:9000/lunie/production-api/issues/164/events/234719bfe4ca4f2ca59cb950bc3c1973/

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3476 

**Description:**

* Prevent sending to the backend txs with NaN amount values.
* Modify `uatom()` function to return an integer value.

Should we implement checks for all parameters needed to build the transaction in all `transactionData()` computed fields?

I think it's a good idea to avoid pass to backend tx that will fail anyway. Maybe we can also send a sentry error if any of the tx params it's not correct, just to help us to figure out what's happening here.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/ActionModal/components/ActionModal.vue [hunk 1]
```diff
@@ -790,45 +800,39 @@ export default {
...
           }
         },
+        /* istanbul ignore next */
         skip() {
-          /* istanbul ignore next */
           return !this.txHash
         },
         query: UserTransactionAdded,
+        /* istanbul ignore next */
         result({ data }) {
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue]: I actually think we should test this as it is more complex. but maybe for another time

File: src/ActionModal/components/ActionModal.vue [hunk 2]
```diff
@@ -651,6 +651,15 @@ export default {
     },
     async submit() {
       this.submissionError = null
+
+      if (
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue]: different idea I want to share: How about returning `{error: true}` to avoid this fancy checking if the object is empty? :D
