### PR TITLE
Ana/3133 loader on networks page missing

### LINKED ISSUE #3133: Loader on Networks Page missing
**Describe the bug**

networks page needs a loader

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3133

**Description:**

I added the simple loader (`TmDataLoading.vue`) to the Networks page

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
Oops, it seems this messed up with the unit tests... Makes sense

File: src/components/network/PageNetworks.vue [hunk 1]
```diff
@@ -1,6 +1,7 @@
 <template>
   <TmPage data-title="Network" class="page" hide-header>
```
Comment (faboweb) [inline src/components/network/PageNetworks.vue]: I will accept the PR but want to show you that TmPage already has logic for loading states. Check PageValidator

Comment (Bitcoinera) [reply src/components/network/PageNetworks.vue]: Yes, I saw! Thank you for the hint :wink: !
