### PR TITLE
Fabo/4470 fix amp in names

### LINKED ISSUE #4470: Validator cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9 alias "amp;amp:amp;amp;amp;..."
There is a validator whose name, it seems, we have never properly displayed. It is this one: https://app.lunie.io/cosmos-hub/validators/cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9

But, as you can see in Bigdipper, it is just an ampersand what we should be displaying: https://cosmos.bigdipper.live/validator/cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9

Also there are a couple of validators in Kusama experiencing the same issue, also with the ampersand I belive.

So this is the "ampersand issue"

### PR DESCRIPTION
**Pull request by faboweb**
Closes #4470 

On db write and then read again and then write again, we double escape the names

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by Bitcoinera** [comment]
It works! :tada: 

image

File: api/lib/stores/block-store.js [hunk 1]
```diff
@@ -262,8 +262,7 @@ class BlockStore {
 
 function enrichValidator(validatorInfo, validator) {
   const picture = validatorInfo ? validatorInfo.picture : undefined
-  const name =
-    validatorInfo && validatorInfo.name ? validatorInfo.name : validator.name
+  const name = validator.name || formatBech32Reducer(validator.operatorAddress)
```
Comment (Bitcoinera) [inline api/lib/stores/block-store.js:265]: Where is this function `formatBech32Reducer` coming from?
