### PR TITLE
Fabo/handle some failing queries

### LINKED ISSUE #3447: Failed Fetch bug (Sentry)
I suppose most of these result from the `update` function not properly handling a case where there is no value, like when the fetch fails.

### PR DESCRIPTION
**Pull request by faboweb**
Closes #3447

**Description:**

Handles the case in the GQL update functions that the query fails

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/ActionModal/components/ActionModal.vue [hunk 1]
```diff
@@ -746,6 +742,11 @@ export default {
         }
       },
       update(data) {
+        if (!data.overview) {
+          return {
+            totalRewards: 0
```
Comment (jbibla) [inline src/ActionModal/components/ActionModal.vue]: shouldn't the API always return this, instead of adding conditionals to all our queries?

File: src/ActionModal/components/DelegationModal.vue [hunk 2]
```diff
@@ -385,6 +385,9 @@ export default {
           address: this.address,
           denom: this.denom
         }
+      },
+      update(data) {
+        return data.balance || { amount: 0 }
```
Comment (jbibla) [inline src/ActionModal/components/DelegationModal.vue]: shouldn't the API always return this, instead of adding conditionals to all our queries?

File: src/ActionModal/components/UndelegationModal.vue [hunk 3]
```diff
@@ -324,6 +324,33 @@ export default {
         return data.delegations
       }
     },
+    balance: {
+      query: gql`
+        query BalanceModalPropos(
```
Comment (jbibla) [inline src/ActionModal/components/UndelegationModal.vue]: what is `BalanceModalPropos` ?

File: src/ActionModal/components/UndelegationModal.vue [hunk 4]
```diff
@@ -364,7 +391,7 @@ export default {
       },
       update(data) {
         /* istanbul ignore next */
-        return data.validators
+        return data.validators || []
```
Comment (jbibla) [inline src/ActionModal/components/UndelegationModal.vue]: shouldn't the API always return this, instead of adding conditionals to all our queries?

File: src/ActionModal/components/ActionModal.vue (hunk 1 above)
Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: what happens if the fetch from the API fails though?

File: src/ActionModal/components/UndelegationModal.vue (hunk 3 above)
Comment (faboweb) [reply src/ActionModal/components/UndelegationModal.vue]:
```suggestion
        query Balance (
```

File: src/ActionModal/components/ActionModal.vue (hunk 1 above)
Comment (jbibla) [reply src/ActionModal/components/ActionModal.vue]: we should be using the error option, no?

https://vue-apollo.netlify.com/api/smart-query.html#options

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: did you experiment with that? how should we use this? does this skip the update function?

Comment (jbibla) [reply src/ActionModal/components/ActionModal.vue]: no i haven't tried it. from an architecture perspective, the API should always return the data we expect. if it doesn't there is likely an error with the API / server which we should catch the _vue-apollo_ way. 

the approach in this PR seems to be handling backend issues in the frontend which seems a bit funny to me. but i am not certain about this. and if this is a temporary fix for some problem we have now then we can certainly merge and address the underlying issues later.

https://learn.hasura.io/graphql/vue/queries/3-handle-errors

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: I think there is a misunderstanding:
This doesn't handle issues with the backend but with the client losing its connection to the internet or similar issues. In this case, the backend can't serve the correct data.

Comment (jbibla) [reply src/ActionModal/components/ActionModal.vue]: yeah, i think i get what you're saying. 

i'm suggesting two things:
1. let's use this vue-apollo `error` option for when there is no internet or the API is broken
2. let's make sure the API returns what the FE needs:

if `!data.overview` than the API is not working and `error` would catch it. shouldn't `data.overview` return `data.overview.totalRewards = 0`?
```
if (!data.overview) {
          return {
            totalRewards: 0
```

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: ok, so you want to show an error "Couldn't get the data to show here" if there is any error? Or you want to show the technical error?

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: this also doesn't solve the Sentry issues if the update function is still triggered and `data.overview` is undefined

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue]: > this also doesn't solve the Sentry issues if the update function is still triggered and `data.overview` is undefined

But we need to know about these errors happening, to be able to fix them. Unless we are already successfully capturing the error in the API and this is just a duplicate.

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: also should each component individually display an error? or a page displays an error?

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue]: It depends. I think in the case of "floating" components like ActionModal it should be shown on the component itself and for "embedded" components it should appear at the top of the page, with small red letters (like we have them now), saying query X failed. IMO

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue]: > But we need to know about these errors happening, to be able to fix them. Unless we are already successfully capturing the error in the API and this is just a duplicate.

we need to know every failing internet connection of a user?

Comment (jbibla) [reply src/ActionModal/components/ActionModal.vue]: so do you think what you're doing in this PR is the right strategy for `update` queries?

**Comment by Bitcoinera** [comment]
I just added as muster the error handling described [here](https://learn.hasura.io/graphql/vue/queries/3-handle-errors) to TmBalance.

What do you think? Should we implement this in all our pages/components?



One thing I like about this approach is that it gives the user enough information so they can also help us fix bugs better and more efficiently.

**Comment by faboweb** [comment]
@bitcoinera the errors should be human readable. I disagree with burdening our users with complex error messages. All errors should be caught by Sentry so we can evaluate them better then the user could.

**Comment by Bitcoinera** [comment]
> @Bitcoinera the errors should be human readable. I disagree with burdening our users with complex error messages. All errors should be caught by Sentry so we can evaluate them better then the user could.

OK, yes, I agree this approach is most likely better. 

So we should always display then a simple "There was an error. Apologies"? Maybe we could add something like "the component Total Balance cannot be displayed correctly"... but I am not sure how we could implement something like that... maybe just a `switch` to select the right error message :woman_shrugging: 
Or is this overcomplicating?

**Comment by faboweb** [comment]
I would simply go for "There was an error so we can't show you this data right now. If this error persists please contact our [Support].". This scales well. But giving some context could also be good.
