### PR TITLE
colw/2657 display full transaction atoms

### LINKED ISSUE #2657: Send transactions still show 0 tokens if less then 0.001
**Describe the bug**

image

**To Reproduce**

Send 0.00001 tokens

**Expected behavior**

Maybe we could show: `< 0.001`? 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by colw**
Closes #2657 

**Description:**

Show full decimal amount

Screenshot 2019-05-27 at 14 35 19

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [x] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/transactions/LiTransaction.vue [hunk 1]
```diff
@@ -20,7 +20,7 @@
       </div>
       <div class="li-tx__content__right">
         <div>
-          Network Fee:&nbsp;<b>{{ fees.amount | toAtoms | shortDecimals }}</b>
+          Network Fee:&nbsp;<b>{{ fees.amount | toAtoms }}</b>
```
Comment (faboweb) [inline src/components/transactions/LiTransaction.vue]: This is not formatting the number. Was that indented?

Comment (colw) [reply src/components/transactions/LiTransaction.vue]: The new filter defined above only works to group thousands, so it wouldn't apply to network fees, generally speaking.

Short answer, no, but it makes no difference. I can put in anyway at a later commit.
