### PR TITLE
Fix polkadot rewards

### LINKED ISSUE #4510: Polkadot rewards are not working
**Describe the bug**

Production db rewards table is empty.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #4510 

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: api/lib/reducers/polkadotV0-reducers.js [hunk 1]
```diff
@@ -450,14 +450,15 @@ function dbRewardsReducer(validatorsDictionary, dbRewards) {
 function rewardReducer(network, validators, reward, reducers) {
   let parsedRewards = []
   Object.entries(reward.validators).forEach((validatorReward) => {
-    if (!validators[validatorReward[0]]) return
+    const validator = validators.find(({ operatorAddress }) => operatorAddress === validatorReward[0])
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js:453]: how about transforming the validators to a dictionary first. should be a lot faster than doing a lookup for every validator

File: api/scripts/getOldPolkadotRewardEras.js [hunk 2]
```diff
@@ -119,13 +120,21 @@ function parseRewards(
             )
 
             staked = stakerExposure ? stakerExposure.value : ZERO
+            // console.log(`staked1:`, staked)
+            staked = isHex(staked) ? new BN(staked.substr(2, staked.length - 2), 16) : new BN(staked)
```
Comment (faboweb) [inline api/scripts/getOldPolkadotRewardEras.js:124]: that looks very hacky. why is staked a hex?

File: api/scripts/getOldPolkadotRewardEras.js [hunk 3]
```diff
@@ -332,13 +344,29 @@ async function main() {
...
-  const storableRewards = _.uniqBy(lunieRewards
-    ? lunieRewards.filter(({ amount }) => amount > 0)
-    : [], reward => `${reward.address}_${reward.validator}_${reward.height}_${reward.chain_id}`) // HACK somehow we get some rewards twice which causes the insert to fail 
+  // const storableRewards = _.uniqBy(lunieRewards
+  //   ? lunieRewards.filter(({ amount }) => amount > 0)
+  //   : [], reward => `${reward.address}_${reward.validator.id}_${reward.height}_${reward.chain_id}`) // HACK somehow we get some rewards twice which causes the insert to fail 
+  
+  let storableRewards = []
+  lunieRewards.filter(({ amount }) => parseFloat(amount) > 0).forEach(reward => {
+    if (!storableRewards.find(storableReward => storableReward.address === reward.address && storableReward.validatorAddress === reward.validatorAddress && storableReward.height === reward.height && storableReward.chain_id === reward.chain_id )) {
```
Comment (faboweb) [inline api/scripts/getOldPolkadotRewardEras.js:356]: can you comment what this check does?

File: api/scripts/getOldPolkadotRewardEras.js (hunk 2 above)
Comment (mariopino) [reply api/scripts/getOldPolkadotRewardEras.js:124]: Sometimes api returns either a integer or an hex, the old code was expecting a BN.

File: api/lib/reducers/polkadotV0-reducers.js [hunk 4]
```diff
@@ -412,10 +412,14 @@ function extractInvolvedAddresses(lunieTransactionType, signer, message) {
 
 function rewardsReducer(network, validators, rewards, reducers) {
   const allRewards = []
+  let validatorsDict = []
```
Comment (Bitcoinera) [inline api/lib/reducers/polkadotV0-reducers.js:415]: looks more like an Array rather than a dictionary?

Comment (mariopino) [reply api/lib/reducers/polkadotV0-reducers.js:415]: yep, old school code ^^ something cleaner/better?

File: api/scripts/getOldPolkadotRewardEras.js (hunk 3 above)
Comment (mariopino) [reply api/scripts/getOldPolkadotRewardEras.js]: Removed, as I dont see duplicates in results.

**Comment by mariopino** [comment]
Rewards populated on staging up to era 42, doing the same for kusama up to era 1033!

**Comment by mariopino** [comment]
mmmm, for kusama it works but the clean old rewards delete many rows :-/ as the query include `_lt` operator which needs a numeric data type for the column.

Soo we need to change column data type from text to numeric in all rewards tables, that means we need to delete the all the existent data as it's a primary key and doesn't allow change the type and rerun the rewards script for all networks again.

File: api/lib/reducers/polkadotV0-reducers.js (hunk 4 above)
Comment (faboweb) [reply api/lib/reducers/polkadotV0-reducers.js:415]:
```suggestion
  let validatorsDict = {}
```

File: api/lib/reducers/polkadotV0-reducers.js [hunk 5]
```diff
@@ -412,10 +412,14 @@ function extractInvolvedAddresses(lunieTransactionType, signer, message) {
...
+  validators.forEach(validator => { 
+    validatorsDict[validator.operatorAddress] = validator
+  })
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js:418]:
```suggestion
  const validatorsDict = keyBy(validators, "operatorAddress")
```

File: api/lib/reducers/polkadotV0-reducers.js [hunk 6]
```diff
@@ -449,11 +453,12 @@ function dbRewardsReducer(validatorsDictionary, dbRewards) {
...
 function rewardReducer(network, validators, reward, reducers) {
   let parsedRewards = []
+
   Object.entries(reward.validators).forEach((validatorReward) => {
     if (!validators[validatorReward[0]]) return
     const lunieReward = {
-      id: validators[validatorReward[0]].operatorAddress,
-      ...reducers.coinReducer(network, validatorReward[1]),
+      id: validatorReward[0],
+      ...reducers.coinReducer(network, validatorReward[1].toString(10)),
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js:461]: can we do a `toJSON` or `toHuman` somewhere to prevent these hacks?

File: api/scripts/getOldPolkadotRewardEras.js (hunk 2 above)
Comment (faboweb) [reply api/scripts/getOldPolkadotRewardEras.js:139]: see above: can we call a toHuman somewhere?

File: api/lib/reducers/polkadotV0-reducers.js [hunk 7]
```diff
@@ -413,9 +413,7 @@ function extractInvolvedAddresses(lunieTransactionType, signer, message) {
 function rewardsReducer(network, validators, rewards, reducers) {
   const allRewards = []
   let validatorsDict = []
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js]:
```suggestion
```

File: api/lib/reducers/polkadotV0-reducers.js [hunk 8]
```diff
@@ -412,10 +412,12 @@ function extractInvolvedAddresses(lunieTransactionType, signer, message) {
 
 function rewardsReducer(network, validators, rewards, reducers) {
   const allRewards = []
+  let validatorsDict = {}
+  const validatorsDict = keyBy(validators, "operatorAddress")
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js:416]:
```suggestion
  const validatorsDict = _.keyBy(validators, "operatorAddress")
```

File: api/lib/reducers/polkadotV0-reducers.js [hunk 9]
```diff
@@ -412,10 +412,12 @@ function extractInvolvedAddresses(lunieTransactionType, signer, message) {
 
 function rewardsReducer(network, validators, rewards, reducers) {
   const allRewards = []
+  let validatorsDict = {}
```
Comment (faboweb) [inline api/lib/reducers/polkadotV0-reducers.js:415]:
```suggestion
```

File: api/scripts/getOldPolkadotRewardEras.js [hunk 10]
```diff
@@ -19,7 +19,8 @@ if (config.SENTRY_DSN) {
 const currentEraArg = require('minimist')(process.argv.slice(2))
 let currentEra = currentEraArg['currentEra']
 const networkId = currentEraArg['network']
-const db = database(config)(networkId)
+const dbName = networkId.replace("-", "_")
```
Comment (faboweb) [inline api/scripts/getOldPolkadotRewardEras.js:22]:
```suggestion
const schema = networkId.replace("-", "_")
```

File: api/scripts/getOldPolkadotRewardEras.js [hunk 11]
```diff
@@ -19,7 +19,8 @@ if (config.SENTRY_DSN) {
...
+const db = database(config)(dbName)
```
Comment (faboweb) [inline api/scripts/getOldPolkadotRewardEras.js:23]:
```suggestion
const db = database(config)(schema)
```

File: api/scripts/getOldPolkadotRewardEras.js [hunk 12]
```diff
@@ -40,7 +41,7 @@ function cleanOldRewards(minDesiredEra) {
   if (minDesiredEra >= 0) {
     return db.query(`
       mutation {
-        delete_${networkId}_rewards(where:{height: {_lt: "${minDesiredEra}"}}) {
+        delete_${dbName}_rewards(where:{height: {_lt: "${minDesiredEra}"}}) {
```
Comment (faboweb) [inline api/scripts/getOldPolkadotRewardEras.js:44]:
```suggestion
        delete_${schema}_rewards(where:{height: {_lt: "${minDesiredEra}"}}) {
```

File: api/lib/reducers/polkadotV0-reducers.js (hunk 6 above)
Comment (mariopino) [reply api/lib/reducers/polkadotV0-reducers.js:458]: The problem there is that toHuman() convert amounts to main denom and includes the denom i.e `9.345 DOT`. Same as `toJSON` I think (need to test, talking from memory). I think it's correct to convert the BN to base 10 number in this case.

**Comment by mariopino** [comment]
Tested with kusama, polkadot and westend in staging and production db.

File: api/scripts/getOldPolkadotRewardEras.js [hunk 13]
```diff
@@ -1,11 +1,26 @@
 const database = require('../lib/database')
 const config = require('../config')
-const db = database(config)('kusama')
```
Comment (Bitcoinera) [inline api/scripts/getOldPolkadotRewardEras.js:3]: Oops, no wonder that polkadot had no rewards :sweat_smile:

File: api/scripts/getOldPolkadotRewardEras.js [hunk 14]
```diff
@@ -331,29 +349,39 @@ async function main() {
     polkadotAPI.reducers
   )
   console.timeEnd('parsing lunie rewards')
```
Comment (Bitcoinera) [inline api/scripts/getOldPolkadotRewardEras.js:351]: Can we maybe already remove all this benchmarking stuff? We are not using them anymore, are we?

File: api/scripts/getOldPolkadotRewardEras.js [hunk 15]
```diff
@@ -115,17 +133,19 @@ function parseRewards(
...
             const stakerExposure = exposure.others.find(
-              ({ who }) => who === delegator
+              ({ who }) => who.toString() === delegator
             )
 
             staked = stakerExposure ? stakerExposure.value : ZERO
+            staked = isHex(staked) ? new BN(staked.substr(2, staked.length - 2), 16) : new BN(staked)
           }
-
+
```
Comment (Bitcoinera) [inline api/scripts/getOldPolkadotRewardEras.js:142]: ? And this tabulation here?

File: api/scripts/getOldPolkadotRewardEras.js [hunk 16]
```diff
@@ -115,17 +133,19 @@ function parseRewards(
...
+            staked = isHex(staked) ? new BN(staked.substr(2, staked.length - 2), 16) : new BN(staked)
           }
-
+          
           value = available
             .minus(validatorCut)
             .times(staked)
             .dividedBy(exposureTotal)
             .plus(validatorId === delegator ? validatorCut : ZERO)
+
```
Comment (Bitcoinera) [inline api/scripts/getOldPolkadotRewardEras.js:148]: Why did you add these lines? I think it was better before

File: api/scripts/getOldPolkadotRewardEras.js (hunk 14 above)
Comment (mariopino) [reply api/scripts/getOldPolkadotRewardEras.js:351]: I think they are useful, i.e when debugging the logs in grafana.

File: api/scripts/getOldPolkadotRewardEras.js (hunk 16 above)
Comment (mariopino) [reply api/scripts/getOldPolkadotRewardEras.js]: True, removed!

File: api/scripts/getOldPolkadotRewardEras.js (hunk 15 above)
Comment (mariopino) [reply api/scripts/getOldPolkadotRewardEras.js]: reemoved!

File: api/lib/reducers/polkadotV0-reducers.js (hunk 6 above)
Comment (faboweb) [reply api/lib/reducers/polkadotV0-reducers.js:458]: :/ please check it when you find time. this is really hard to read/understand
