### PR TITLE
Ana/fix polkadot import account wasm crypto

### LINKED ISSUE #3901: Polkadot import account with Schnorrkel fails on first run
It is not waiting for the `wasm-crypto` package to be loaded so there is no `addFromUri` function

Bug screenshot:

image

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3901

**Description:**

Fixes this (wasn't waiting for the wasm-crypto package to be initialized):

image

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/vuex/modules/wallet.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ function getCosmosAddressCreator(bech32Prefix) {
 async function createPolkadotAddress(seedPhrase, addressPrefix) {
   const [{ Keyring }] = await Promise.all([
     import("@polkadot/api"),
+    import("@polkadot/wasm-crypto"),
```
Comment (faboweb) [inline src/vuex/modules/wallet.js:13]: is that also needed for signing or only for address creation?

Comment (faboweb) [reply src/vuex/modules/wallet.js:13]: for signing it is not needed?

Comment (Bitcoinera) [reply src/vuex/modules/wallet.js:13]: Let me check if I get it there too

Comment (Bitcoinera) [reply src/vuex/modules/wallet.js:13]: no, signing works just fine (for Schnorrkel accounts).

For Edwards accounts that get "crunched" I still get BadProof though

Comment (faboweb) [reply src/vuex/modules/wallet.js:13]: what does crunched mean?

Comment (Bitcoinera) [reply src/vuex/modules/wallet.js:13]: Well, in this case I want to mean the addresses that get "destroyed".

Like I had Mario's one that looked like this `JGVLUnieotWLyg25D1uF88EahxmGjc7Dhe2fHUjA5ziBd7i`, but after the Schnorrkel thing it looks like this: `16hApVhutE942rs6G9FrVKbPHjgBANM4qpXmRvC8ENojcxkv` 

And now I cannot sign any transaction with that transformed address. I always get `BadProof`
