### PR TITLE
colw/Refactor Proposal tally display code

### LINKED ISSUE #2430: Proposal tally doesn't sum to 100%
**Describe the bug**

Screen Shot 2019-04-05 at 7 58 31 PM

### PR DESCRIPTION
**Pull request by colw**
Closes #2430 

**Description:**

Proposal integer tallies do not sum to 100%, so we need to mask this by either rounding up/down numbers, or displaying more decimal places so the original problem is less obvious.

The solution here will display percentages rounded to 2 decimals places:

Screenshot 2019-05-07 at 21 03 54

Code changes:
- Add convenience method for checking DepositPeriod status
- Add filter method for percentages
- Replace individual tally methods with filtering
- Replace if structure with switch
- Replace `percentInt` with `percent` (default 2 decimal places)

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [x] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by colw** [comment]
How does this look @jbibla ?

_Note that I still need to fix the case where it adds to 99.99%_

**Comment by colw** [comment]
@jbibla Let me know if it's important the numbers add to exactly 100%, and I'll put it in.

**Comment by faboweb** [comment]
I think it's ok. I was just thinking that the added decimals create more noise. But your call.

**Comment by jbibla** [comment]
this is how we show decimals on the validator table, so for the sake of consistency i think 2 decimal places makes sense.

@colw how much work would it be to have them always add up to 100?

**Comment by colw** [comment]
@jbibla I could do it today. Potential it can be reused in other parts, so there's value.

**Comment by colw** [comment]
Sum to 1 or 2 decimal places:

Screenshot 2019-05-09 at 21 47 03

File: src/utils/index.js [hunk 1]
```diff
@@ -0,0 +1,39 @@
+// This will take an object and for each (k,v) will return
+// v rounded such that the sum of all v is 100.
+export const roundObjectPercentages = dataMap => {
+  // This algorithm workson integers and we want 2 decimal places.
+  // So round up first.
+  let asArray = Object.entries(dataMap).map(keyValue => {
```
Comment (faboweb) [inline src/utils/index.js]: Maybe something like this would be more readable?

```suggestion
  let asArray = Object.entries(dataMap).map(([key, value])=> {
```

File: src/utils/index.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+  })
+
+  // Calculate difference from 100%
+  var margin =
+    10000 -
+    asArray.reduce(function(acc, x) {
+      return acc + Math.round(x[1])
+    }, 0)
+
+  const cmp = (a, b) => {
```
Comment (faboweb) [inline src/utils/index.js]: what's compared here?

File: src/utils/index.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+  // This algorithm workson integers and we want 2 decimal places.
+  // So round up first.
+  let asArray = Object.entries(dataMap).map(keyValue => {
+    keyValue[1] = keyValue[1] * 100
+    return keyValue
+  })
+
+  // Calculate difference from 100%
+  var margin =
+    10000 -
```
Comment (faboweb) [inline src/utils/index.js]: why 10000?

File: src/utils/index.js [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+  const cmp = (a, b) => {
+    return b[1] - Math.round(a[1]) - a[1]
+  }
+
+  // Sort and distribute difference amongst values
+  asArray.sort(cmp)
+  const result = asArray.map(function(x, i) {
+    const rounded = [
+      x[0],
+      (Math.round(x[1]) + (margin > i) - (i >= asArray.length + margin)) / 100.0
```
Comment (faboweb) [inline src/utils/index.js]: I think this line would love a small comment

File: src/utils/index.js [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+    asArray.reduce(function(acc, x) {
+      return acc + Math.round(x[1])
+    }, 0)
+
+  const cmp = (a, b) => {
+    return b[1] - Math.round(a[1]) - a[1]
+  }
+
+  // Sort and distribute difference amongst values
+  asArray.sort(cmp)
```
Comment (colw) [inline src/utils/index.js]: // const test = 1

File: src/utils/index.js (hunk 4 above)
Comment (colw) [inline src/utils/index.js]:
```suggestion
      // A small comment
      (Math.round(x[1]) + (margin > i) - (i >= asArray.length + margin)) / 100.0
```

File: src/utils/index.js (hunk 1 above)
Comment (colw) [reply src/utils/index.js]: Good one!

File: src/utils/index.js (hunk 2 above)
Comment (colw) [reply src/utils/index.js]: True. I'll rename it

File: src/utils/index.js (hunk 3 above)
Comment (colw) [reply src/utils/index.js]: I'll make this clearer. Scaling for 100%, accounting for 2 extra decimal places.

File: src/utils/index.js (hunk 4 above)
Comment (colw) [reply src/utils/index.js]: It's good you say so actually. I did base this of an algorithm I found, and I thought I understood it completely until now.

Comment (colw) [reply src/utils/index.js]: I've added a basic description and a link to a stack overflow article on the matter. I hope hat's sufficient. It can do a better job of describing what's happening, without cluttering up the code base with a larger explanation.
