### PR TITLE
Jordan/3489 intercom

### LINKED ISSUE #3489: Intercom doesn't work on Lunie mobile
**Describe the #1 bug**

Testnet networks images not loading

**Describe the #2 bug**

Indent bug in the Terms of Services section.

When you tap on "Terms of Services" or "Privacy Policy" and start scrolling, once you tap the “Menu” icon, the nav will disappear and make this bug.

**Describe the #3 bug**

Intercom bug. 

The Help / Feedback button is not working on my device, it doesn’t do anything.

**Smartphone (please complete the following information):**
 - Device: iOS iP11
 - OS: iOS11 I guess?
 - Browser 
 - Version

### PR DESCRIPTION
**Pull request by jbibla**
Closes #3489

**Description:**
- it is necessary to register users with intercom before opening the mobile messenger. i can confirm this works on my local xcode and assume the fix will work on Android and iOS devices

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by mariopino** [comment]
> Closes #3489
> 
> **Description:**
> 
> * it is necessary to register users with intercom before opening the mobile messenger. i can confirm this works on my local xcode and assume the fix will work on Android and iOS devices
> 
> Thank you! 🚀
> 
> For contributor:
> 
> * [x]  Added changes entries. Run `yarn changelog` for a guided process.
> * [x]  Reviewed `Files changed` in the github PR explorer
> * [ ]  Attach screenshots of the UI components on the PR description (if applicable)
> * [ ]  Scope of work approved for big PRs
> 
> For reviewer:
> 
> * [ ]  Manually tested the changes on the UI

Arg! User registration was in the original PR and I remove it to not spam our intercom channel :-(

File: src/vuex/modules/intercom.js [hunk 1]
```diff
@@ -15,7 +15,11 @@ export default () => {
     },
     actions: {
       displayMessenger({ state }) {
-        if (state.mobileApp) state.intercom.displayMessenger()
+        if (state.mobileApp) {
+          // we have to register users otherwise intercom will not open
+          state.intercom.registerUnidentifiedUser();
```
Comment (mariopino) [inline src/vuex/modules/intercom.js]: Great! This way we do not spam the channel with user registration messages!
