### PR TITLE
Benji/2164 redirect 404 validator not found

### LINKED ISSUE #2164: Redirect to 404 on not found validator
**Describe the bug**

When I go to a validator route that doesn't exist the app stays empty

**To Reproduce**

go to `https://localhost:9080/#/staking/validators/cosmosvaloper1lknsahxsn9yfxr7q400y6xyezxpqq4c90xrn8d`

**Expected behavior**

The app redirects to `/404`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by thebkr7**
Closes #2164

**Description:**

Displays 404 component when an invalid validators address is entered.

Thank you! 🚀

---

For contributor:

- [x] Added changes entries. Run `yarn changelog` for a guided process.
- [x] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by thebkr7** [comment]
Writing tests

**Comment by thebkr7** [comment]
@jbibla Wrote a unit test but the CodeClimate/diff-coverage is still the same. Is it only looking at e2e tests?

**Comment by faboweb** [comment]
To see the coverage install the codeclimate chrome extension. After go to the "Files changed" view on GItHub

**Comment by thebkr7** [comment]
Thanks, I do have the extension but my test is testing the functionality that it is saying is not tested. I will adjust the test.

File: src/components/common/TmPage.vue [hunk 1]
```diff
@@ -22,6 +22,17 @@
         <slot v-else-if="dataEmpty" name="no-data">
           <TmDataEmpty />
         </slot>
+        <slot v-else-if="notFound" name="no-data">
+          <TmDataMsg title="Woops Validator Not Found">
```
Comment (jbibla) [inline src/components/common/TmPage.vue]:
```suggestion
          <TmDataMsg title="Validator Not Found">
```

Comment (jbibla) [reply src/components/common/TmPage.vue]: 😆

File: src/components/common/TmPage.vue [hunk 2]
```diff
@@ -22,6 +22,17 @@
...
+            <div slot="subtitle">
+              Please visit our
```
Comment (jbibla) [inline src/components/common/TmPage.vue]:
```suggestion
              Please visit the
```

File: src/components/staking/PageValidator.vue [hunk 3]
```diff
@@ -4,7 +4,7 @@
     :loading="delegates.loading"
     :loaded="delegates.loaded"
     :error="delegates.error"
-    :data-empty="!validator"
+    :not-found="!validator"
```
Comment (jbibla) [inline src/components/staking/PageValidator.vue]: nice

File: src/components/common/TmPage.vue [hunk 4]
```diff
@@ -22,6 +22,17 @@
         <slot v-else-if="dataEmpty" name="no-data">
           <TmDataEmpty />
         </slot>
+        <slot v-else-if="notFound" name="no-data">
```
Comment (faboweb) [inline src/components/common/TmPage.vue]: is there any case where "empty data" would be different then "not found data"? if it isn't I would advice against the additional case.

Comment (thebkr7) [reply src/components/common/TmPage.vue]: We could just show the dataEmpty page with its default information but we wanted to show the user a link to see all validators when they entered an invalid address. Do you think to keep the code simpler we should just show them the TmDataEmpty page?

Comment (faboweb) [reply src/components/common/TmPage.vue]: No the intention was correct. I agree with showing the better guiding info. But I propose that you overwrite the content of the `no-data` slot (https://vuejs.org/v2/guide/components-slots.html#Fallback-Content) on the `PageValidator` instead of defining this domain specific message in the lower level component `TmPage`.

Comment (thebkr7) [reply src/components/common/TmPage.vue]: I see what you are saying and will make the changes. Thanks
