### PR TITLE
Ana/3965 emoney limit fees

### LINKED ISSUE #3965: e-Money eDKK unable to send with incorrect fee error message with Ledger Nano S
**Describe the bug**
Trying to send eDKK to myself, no matter how little amount of eDKK I try to send myself the modal says I don't have enough to pay the fees, plus the fees cost shows as 0 in the final sending screen message.

Screen Shot 2020-05-04 at 11 44 05 AM

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #3965

**Description:**

OK, so as you can see I was here trying weird stuff with some fixed fees thing when at the end I realized the logic to fix this issue is quite simple...

simply, when the network we are on is e-Money or Kava mainnets, don't apply `adjustFeesToMaxPayable` and that's it.

I also took the chance to refactor SendModal to get `chainAppliedFees` from the API

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/ActionModal/components/ActionModal.vue [hunk 1]
```diff
@@ -724,11 +731,9 @@ export default {
     // limit fees to the maximum the user has
     adjustFeesToMaxPayable() {
       let payable = Number(this.subTotal)
-      // in terra we also have to pay the tax
-      // TODO refactor using a `fixedFee` property
-      if (this.chainAppliedFees) {
-        payable += this.chainAppliedFees
-      }
+      // chainAppliedFees defaults to 0 so we can just add it
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:734]: nice

File: src/ActionModal/components/ActionModal.vue [hunk 2]
```diff
@@ -502,9 +502,16 @@ export default {
...
-        Number(this.subTotal) + this.estimatedFee >
-        this.selectedBalance.amount
+        this.networkId === "emoney-mainnet" ||
+        this.networkId === "kava-mainnet"
+      ) {
+        return Number(this.subTotal) + this.estimatedFee
+      }
+      if (
+        this.gasEstimate &&
+        Number(this.subTotal) + this.estimatedFee > this.selectedBalance.amount
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:514]:
```suggestion
        Number(this.subTotal) + this.estimatedFee > this.selectedBalance.amount
        // emoney-mainnet and kava-mainnet don't allow discounts on fees
        && this.networkId !== "emoney-mainnet"
        && this.networkId !== "kava-mainnet"
```

that avoids the double code in the beginning of the function

Comment (Bitcoinera) [reply src/ActionModal/components/ActionModal.vue:514]: yeah, I thought of doing this too, but I thought it would be a too long of an if statement. 

But I can change it

Comment (faboweb) [reply src/ActionModal/components/ActionModal.vue:514]: I don't mind. pick you.

**Comment by faboweb** [comment]
tests (unit+e2e) are failing

File: src/ActionModal/components/ActionModal.vue [hunk 3]
```diff
@@ -503,15 +503,12 @@ export default {
...
-        this.networkId === "kava-mainnet"
-      ) {
-        return Number(this.subTotal) + this.estimatedFee
-      }
       if (
         this.gasEstimate &&
-        Number(this.subTotal) + this.estimatedFee > this.selectedBalance.amount
+        Number(this.subTotal) + this.estimatedFee >
+          this.selectedBalance.amount &&
+        !this.networkId === "emoney-mainnet" &&
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:510]: nope

File: src/ActionModal/components/ActionModal.vue [hunk 4]
```diff
@@ -503,15 +503,12 @@ export default {
...
+        !this.networkId === "kava-mainnet"
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:511]:
```suggestion
        // emoney-mainnet and kava-mainnet don't allow discounts on fees
        this.networkId !== "emoney-mainnet" &&
        this.networkId !== "kava-mainnet"
```

File: src/ActionModal/components/ActionModal.vue [hunk 5]
```diff
@@ -503,15 +503,12 @@ export default {
     },
     invoiceTotal() {
       // emoney-mainnet and kava-mainnet don't allow discounts on fees
```
Comment (faboweb) [inline src/ActionModal/components/ActionModal.vue:505]:
```suggestion
```

**Comment by Bitcoinera** [comment]
There is no patch for http-proxy yet... any ideas? It is used by `vue/cli-service` itself

image

**Comment by faboweb** [comment]
only used by the dev-server. we can ignore it until there is a patch. e2e tests failed. I restarted them.

**Comment by Bitcoinera** [comment]
Good to go!

File: src/ActionModal/components/SendModal.vue [hunk 6]
```diff
@@ -349,10 +347,15 @@ export default {
         : this.amount
       if (
         this.network.startsWith(`terra`) &&
-        this.selectedBalance.denom !== `LUNA`
+        this.selectedBalance.denom !== `LUNA` &&
+        this.chainAppliedFees &&
```
Comment (faboweb) [inline src/ActionModal/components/SendModal.vue:351]: do we need to wait until those are loaded?

Comment (Bitcoinera) [reply src/ActionModal/components/SendModal.vue:351]: well, yes, otherwise how to calculate the Terra Tax. I needed to add this because otherwise it was erroring as soon as I got to Portfolio

Comment (faboweb) [reply src/ActionModal/components/SendModal.vue:351]: ahh alright this logic already waits until chainAppliedFees is loaded? what if it is loaded for another coin/network and then you switch and reopen the SendModal?

Comment (Bitcoinera) [reply src/ActionModal/components/SendModal.vue:351]: I just checked and it is firing everytime the user changes the network. But it would be good to check once we have the networks navbar on the left
