### PR TITLE
Fix no validator found appears instead of Data loading

### LINKED ISSUE #3270: No validator found appears instead of Data loading
**Describe the bug**

When the validator page is loading, the "Validator Not Found" modal appears instead of the "Data loading" one.

**To Reproduce**

Just try opening validators pages until it takes some timefor it to load.

**Expected behavior**

Data loading modal should be displayed.

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Brave
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

### PR DESCRIPTION
**Pull request by mariopino**
Closes #3270 3270

**Description:**

Just to add TmDataLoading component to PageValidator.vue and display it when `$apollo.queries.validator.loading`.

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

**Comment by colw** [comment]
I see `TmDataEmpty`, but I think you want to show `TmDataLoading`?

Screenshot 2019-12-10 at 13 52 28

**Comment by jbibla** [comment]
yep! thanks colin. we should show the loading screen, not the "no data available" screen.

File: src/components/staking/PageValidator.vue [hunk 1]
```diff
@@ -8,7 +8,8 @@
     data-title="Validator"
     class="small"
   >
-    <template v-if="validator.operatorAddress" slot="managed-body">
+    <TmDataLoading v-if="$apollo.loading" />
```
Comment (jbibla) [inline src/components/staking/PageValidator.vue]:
```suggestion
    <TmDataLoading v-if="$apollo.queries.validator.loading" />
```

Comment (jbibla) [reply src/components/staking/PageValidator.vue]: if i'm not mistaken, this will only show when `validator` is loading - we don't need to wait for `delegation` or `rewards` to load the page.

@colw would you agree?

Comment (colw) [reply src/components/staking/PageValidator.vue]: Yes. We should always show something as fast as possible.
