### PR TITLE
Fabo/wait for rewards

### LINKED ISSUE #2713: Error when withdrawing rewards
Withdrawal failed: Tx.GetMsgs() must return at least one message in list

### PR DESCRIPTION
**Pull request by faboweb**
Closes #2713

This will now disable the withdraw button until the needed validator rewards are loaded to prevent users from starting a withdraw process before. When that happens, the top 5 validator script fails.

### CODE REVIEW

File: src/components/common/TmBalance.vue [hunk 1]
```diff
@@ -82,6 +82,16 @@ export default {
     totalRewards() {
       return this.distribution.totalRewards[this.bondDenom]
     },
+    // only be ready to withdraw of the validator rewards are loaded and the user has rewards to withdraw
+    // the validator rewards are needed to filter the top 5 validators to withdraw from
+    readyToWithdraw() {
+      return (
+        Object.values(this.distribution.rewards)
+          .map(rewards => rewards[this.bondDenom])
+          .filter(bondDenomRewards => bondDenomRewards > 0).length > 0 &&
```
Comment (colw) [inline src/components/common/TmBalance.vue]: I feel we should have a getter which computes a list of validators with non zero rewards. It could be used elsewhere

File: src/vuex/getters.js [hunk 2]
```diff
@@ -33,6 +33,10 @@ export const yourValidators = (state, getters) =>
           operator_address in getters.committedDelegations
       )
     : []
+export const validatorsWithRewards = (state, getters) =>
+  Object.entries(state.distribution.rewards)
+    .filter(([, rewards]) => rewards[getters.bondDenom] > 0)
+    .map(([validator]) => validator)
```
Comment (colw) [inline src/vuex/getters.js]: I think you could leave off the last `.map`, since it's useful information that could be used elsewhere.

**Comment by faboweb** [comment]
@colw @jbibla please take care of this PR and release asap! This is a critical fix for our users.
