### PR TITLE
Fabo/block page fix

### LINKED ISSUE #3010: blocks page does not render via URL
1. visit https://app.lunie.io/blocks/1985026
2. it will load forever

3. (if) it loads, it doesn't need to display the date about the transaction list 😄 

Screen Shot 2019-10-01 at 4 21 55 PM

### PR DESCRIPTION
**Pull request by faboweb**
Closes #3010

**Description:**

Thank you! 🚀

---

For contributor:

- [ ] Added changes entries. Run `yarn changelog` for a guided process.
- [ ] Reviewed `Files changed` in the github PR explorer
- [ ] Attach screenshots of the UI components on the PR description (if applicable)
- [ ] Scope of work approved for big PRs

For reviewer:

- [ ] Manually tested the changes on the UI

### CODE REVIEW

File: src/components/network/PageBlock.vue [hunk 1]
```diff
@@ -86,6 +86,7 @@ export default {
     validators: []
   }),
   computed: {
+    ...mapState({ network: state => state.connection.network }),
```
Comment (jbibla) [inline src/components/network/PageBlock.vue]: `...mapState` is used twice?

**Comment by faboweb** [comment]
Yes, in different Formats. thats intended

Jordan Bibla <notifications@github.com> schrieb am Mi., 2. Okt. 2019, 15:04:
